In [27]:
# Dependencies
# Dependencies
import pandas as pd

# load CSV
csv_path = "Resources/2016-FCC-New-Coders-Survey-Data.csv"
code_df =pd.read_csv(csv_path, encoding ='iso-8859-1',low_memory=False)

code_df.head()

# Extract only columns 0, 1, 2, 3, 4, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111
new_coders = code_df.iloc[:, [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111]]
new_coders.head()

# Change "0" to "No" and "1" to "Yes" in response columns
new_coders =new_coders.replace({0.0:"No",1.0:"Yes"})
new_coders.head()

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,...,CountryLive,EmploymentField,EmploymentStatus,Gender,HasChildren,HoursLearning,Income,JobRoleInterest,SchoolDegree,SchoolMajor
0,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,office and administrative support,Employed for wages,male,No,30,32000.0,NaN,"some college credit, no degree",NaN
1,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,food and beverage,Employed for wages,male,NaN,30,15000.0,Front-End Web Developer,"some college credit, no degree",NaN
2,19.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,finance,Employed for wages,male,NaN,20,48000.0,NaN,high school diploma or equivalent (GED),NaN
3,26.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,NaN,20,43000.0,Front-End Web Developer,bachelor's degree,Cinematography And Film
4,20.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,education,Employed for wages,female,NaN,25,6000.0,Full-Stack Web Developer,"some college credit, no degree",NaN

In [ ]:
# load CSV

In [ ]:
# Read with pandas--low_memory required to suppress errors about mixed data types

In [ ]:
# Take only columns 0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111

In [ ]:
# Change reading 0 and 1 to No and Yes, respectively

In [28]:

# Extract rows corresponding only to people who attended a bootcamp
attended_bootcamp = new_coders.loc [new_coders["AttendedBootcamp"]=="Yes"]
attended_bootcamp.count()

Age                     818
AttendedBootcamp        953
BootcampFinish          933
BootcampFullJobAfter    635
BootcampLoanYesNo       934
BootcampName            895
BootcampPostSalary      330
BootcampRecommend       937
ChildrenNumber          148
CityPopulation          823
CodeEventBootcamp        27
CountryLive             825
EmploymentField         476
EmploymentStatus        792
Gender                  833
HasChildren             211
HoursLearning           925
Income                  430
JobRoleInterest         402
SchoolDegree            832
SchoolMajor             622
dtype: int64

In [31]:
# Create DataFrame of the different boot camps that had a significant number of attendees
# Extract rows corresponding only to people who attended a bootcamp


groupedboot= attended_bootcamp[["BootcampName","AttendedBootcamp"]].groupby(['BootcampName']).count()
groupedboot = groupedboot.rename(columns={"BootcampName": "Count"})
groupedboot.head(30)

                          AttendedBootcamp
BootcampName
10x.org.il                               5
4Geeks Academy                           8
AcadGild                                 2
Academia de CÃƒÂ³digo                      4
Academic Work Academy                    1
Academy X                                1
Ada                                      9
Alphappl                                 1
AngelHack Education                      1
Anyone Can Learn To Code                 7
App Academy                             22
Astro Code School                        1
Atlanta Code                             1
Austin Coding Academy                    1
Base10 Academy                           1
Betamore                                 1
Big Nerd Ranch                           2
Bit Bootcamp                             4
Bitmaker Labs                            5
Bloc.io                                 21
BoiseCodeWorks                           2
BrainStation                             3
Byte Academy                             1
CODEcamp Charleston                      2
Camp Code Away                           4
CareerFoundry                            5
Claim Academy                            1
Code 42                                  1
Code Fellows                            21
Code For Progress                        1

In [35]:
# Count how many attendees of each bootcamp would recommend the bootcamp
columns = [
    "BootcampName","BootcampRecommend"]

#  Create a new df for "US" with the columns. 
bootcamp_rec_df = attended_bootcamp.loc[attended_bootcamp["BootcampRecommend"] == "Yes",  columns]
bootcamp_recgroup_df= bootcamp_rec_df.groupby(['BootcampName']).count()

bootcamp_recgroup_df.head(30)

                          BootcampRecommend
BootcampName
10x.org.il                                3
4Geeks Academy                            4
AcadGild                                  2
Academia de CÃƒÂ³digo                       4
Ada                                       8
AngelHack Education                       1
Anyone Can Learn To Code                  5
App Academy                              20
Austin Coding Academy                     1
Base10 Academy                            1
Betamore                                  1
Big Nerd Ranch                            2
Bit Bootcamp                              2
Bitmaker Labs                             3
Bloc.io                                  11
BoiseCodeWorks                            2
BrainStation                              2
Byte Academy                              1
CODEcamp Charleston                       2
Camp Code Away                            2
CareerFoundry                             4
Claim Academy                             1
Code 42                                   1
Code Fellows                             15
Code Institute                            1
Code Platoon                              2
Code Union                                1
CodeCore Bootcamp                         3
CodeCraft School                          1
CodeMasters Academy                       1

In [48]:
# Merge the two created data frames on the name of tbe bootcamp
merge_table = pd.merge(groupedboot, bootcamp_recgroup_df, on="BootcampName")

merge_table

                          AttendedBootcamp  BootcampRecommend
BootcampName
10x.org.il                               5                  3
4Geeks Academy                           8                  4
AcadGild                                 2                  2
Academia de CÃƒÂ³digo                      4                  4
Ada                                      9                  8
AngelHack Education                      1                  1
Anyone Can Learn To Code                 7                  5
App Academy                             22                 20
Austin Coding Academy                    1                  1
Base10 Academy                           1                  1
Betamore                                 1                  1
Big Nerd Ranch                           2                  2
Bit Bootcamp                             4                  2
Bitmaker Labs                            5                  3
Bloc.io                                 21                 11
BoiseCodeWorks                           2                  2
BrainStation                             3                  2
Byte Academy                             1                  1
CODEcamp Charleston                      2                  2
Camp Code Away                           4                  2
CareerFoundry                            5                  4
Claim Academy                            1                  1
Code 42                                  1                  1
Code Fellows                            21                 15
Code Institute                           1                  1
Code Platoon                             2                  2
Code Union                               1                  1
CodeCore Bootcamp                        5                  3
CodeCraft School                         1                  1
CodeMasters Academy                      1                  1
...                                    ...                ...
PDX Code Guild                           2                  1
Prime Digital Academy                   30                 25
RefactorU                                4                  2
Ruby On The Beach                        1                  1
Rutgers Coding Bootcamp                  4                  3
Sabio.la                                 4                  3
Science to Data Science                  1                  1
SeedPaths                                1                  1
Skillcrush                               4                  3
Software Guild                          10                  8
Stackademy                               1                  1
Starter League                           3                  1
Startup Institute                        7                  4
Tech Academy Portland                    3                  2
Tech Talent South                       12                  8
Telegraph Academy                        2                  2
The Data Incubator                       1                  1
The Firehose Project                    16                 13
The Iron Yard                           40                 31
Thinkful                                 6                  5
Turing                                  27                 26
V School                                 3                  1
Viking Code School                      10                 10
We Can Code IT                           3                  1
We Got Coders                            2                  2
Wyncode                                  6                  3
Zip Code Wilmington                      3                  1
codeU                                    1                  1
devCodeCamp                              4                  4
tradecraft                               3                  1

[116 rows x 2 columns]

In [49]:
# Calculate percentage of eac bootcamp's students who are recommenders
merge_table["Percent Recommend"] = merge_table['BootcampRecommend'] / \
merge_table['AttendedBootcamp']*100

merge_table = merge_table.sort_values((["Percent Recommend"]),ascending=False)
merge_table["Percent Recommend"] = merge_table["Percent Recommend"].astype(float).map("{:,.2f}%".format)
merge_table

,AttendedBootcamp,BootcampRecommend,Percent Recommend
BootcampName,,,
CodeCraft School,1,1,100.00%
LEARN Academy,3,3,100.00%
Origin Code Academy,1,1,100.00%
CodeaCamp,8,8,100.00%
Codecademy Labs,2,2,100.00%
Viking Code School,10,10,100.00%
Coder Factory,2,2,100.00%
Coder Foundry,1,1,100.00%
Coder's Lab,1,1,100.00%
Stackademy,1,1,100.00%
Operation Spark,1,1,100.00%
Microsoft Research Data Science Summer School,1,1,100.00%
Omaha Code School,2,2,100.00%
DESIGNATION,1,1,100.00%
Dev Academy,13,13,100.00%
Grand Circus,3,3,100.00%
Dev League,3,3,100.00%
Science to Data Science,1,1,100.00%
Grace Hopper Academy,3,3,100.00%
The Data Incubator,1,1,100.00%
DigitalCrafts,2,2,100.00%
EHD Academy,2,2,100.00%
Eleven Fifty Academy,2,2,100.00%
Fullstack Academy,6,6,100.00%
Telegraph Academy,2,2,100.00%
CodeMasters Academy,1,1,100.00%
Founders & Coders,1,1,100.00%
Code Union,1,1,100.00%
Makers Academy,12,12,100.00%
Le Wagon,1,1,100.00%
...,...,...,...
Coding Dojo,18,11,61.11%
Codeup,10,6,60.00%
Bitmaker Labs,5,3,60.00%
10x.org.il,5,3,60.00%
CodeCore Bootcamp,5,3,60.00%
Startup Institute,7,4,57.14%
Galvanize,20,11,55.00%
Coder Camps,11,6,54.55%
Bloc.io,21,11,52.38%
RefactorU,4,2,50.00%
Camp Code Away,4,2,50.00%
Codesmith,4,2,50.00%
PDX Code Guild,2,1,50.00%
Devschool,4,2,50.00%
Digital House,2,1,50.00%
Fire Bootcamp,2,1,50.00%
4Geeks Academy,8,4,50.00%
HackerYou,2,1,50.00%
LearningFuze,2,1,50.00%
Bit Bootcamp,4,2,50.00%
Metis,2,1,50.00%
Mobile Makers Academy,2,1,50.00%
Wyncode,6,3,50.00%
Zip Code Wilmington,3,1,33.33%
Coding House,3,1,33.33%
We Can Code IT,3,1,33.33%
V School,3,1,33.33%
Starter League,3,1,33.33%
tradecraft,3,1,33.33%
Codify Academy,4,1,25.00%

In [47]:
# Export to excel and remove index
merge_table.to_excel("bootcamp_recommend.xlsx",index= False)